###############################################################################
#  Copyright (c) 2008, 2023 Wind River Systems and others.
#  All rights reserved. This program and the accompanying materials
#  are made available under the terms of the Eclipse Public License v2.0
#  which accompanies this distribution, and is available at
#  http://www.eclipse.org/legal/epl-v20.html
# 
#  Contributors:
#      Wind River Systems - initial API and implementation
###############################################################################
bin.includes = feature.xml,\
               feature.properties,\
               p2.inf

