#docker volume create --driver local --opt type=tmpfs --opt device=tmpfs --opt o=size=100m,uid=1000
- name: create jobs-volume
  community.docker.docker_volume:
    name: "{{ role_name }}-{{act_item.servmame}}-jobs-volume"
    driver_options: 
      type: tmpfs
      device: tmpfs
      o: "size=100m,uid=1000,gid=1000"
    state: present
  when: (docker_jobs_info_volumes.volumes is defined) and (docker_jobs_info_volumes.volumes | length==0)
- name: start tmp jobs-volume container
  ansible.builtin.shell: "docker run --rm -d -v {{ role_name }}-{{act_item.servmame}}-jobs-volume:/jobs --name jenkinstmp busybox sleep infinity"
  when: (docker_jobs_info_volumes.volumes is defined) and (docker_jobs_info_volumes.volumes | length==0)
#- name: change owner jobs-volume
#  ansible.builtin.shell: "docker exec jenkinstmp chown 1000:1000 /jobs"
#  when: (docker_jobs_info_volumes.volumes is defined) and (docker_jobs_info_volumes.volumes | length==0)
- name: put jobs into jobs-volume
  ansible.builtin.shell: "docker cp /mylyn-config-dir/{{ role_name }}/{{act_item.data_dir}}/jenkins_home/jobs jenkinstmp:/ && docker stop jenkinstmp"
  when: (docker_jobs_info_volumes.volumes is defined) and (docker_jobs_info_volumes.volumes | length==0)
