- name: create jks-volume
  community.docker.docker_volume:
    name: "{{ role_name }}-{{act_item.servmame}}-jks-volume"
    state: present
- name: change owner jks-volume
  ansible.builtin.shell: "docker run --rm -d -v {{ role_name }}-{{act_item.servmame}}-jks-volume:/jks busybox chown 1000:1000 /jks"

- name: start tmp jks-volume container
  ansible.builtin.shell: "docker run --rm --entrypoint /usr/bin/env -d -v {{ role_name }}-{{act_item.servmame}}-jks-volume:/jks --name jenkinstmp 127.0.0.1:5000/{{act_item.servmame}}:1 sleep infinity"

- name: put jks into jks-volume
  ansible.builtin.shell: "docker cp /mylyn-config-dir/certs/ jenkinstmp:/jks"
- name: build jenkins.jks into jks-volume
  ansible.builtin.shell:  |
    docker exec jenkinstmp bash -c 'ls -al /jks
    ls -al /jks/certs
    openssl pkcs12 -export -out /jks/certs/jenkins.p12 \
      -passout 'pass:changeit' -inkey /jks/certs/mylynmstr01.key \
      -in /jks/certs/mylynmstr01.crt -certfile /jks/certs/rootca.crt -name mylyn.local
    keytool -importkeystore -srckeystore /jks/certs/jenkins.p12 \
      -srcstorepass 'changeit' -srcstoretype PKCS12 \
      -srcalias mylyn.local -deststoretype JKS \
      -destkeystore /jks/jenkins.jks -deststorepass 'changeit' \
      -destalias mylyn.local
    chmod 700 /jks
    chmod 600 /jks/jenkins.jks
    rm -r /jks/certs
    ls -al /jks'
    docker stop jenkinstmp
