/*******************************************************************************
 * Copyright (c) 2010 Tasktop Technologies and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 *******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 

package org.eclipse.mylyn.internal.hudson.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hudson.model.OverallLoadStatistics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hudson.model.OverallLoadStatistics">
 *   &lt;complexContent>
 *     &lt;extension base="{}hudson.model.LoadStatistics">
 *       &lt;sequence>
 *         &lt;element name="totalQueueLength" type="{}hudson.model.MultiStageTimeSeries" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hudson.model.OverallLoadStatistics", propOrder = {
    "totalQueueLength"
})
@SuppressWarnings("all")
public class HudsonModelOverallLoadStatistics
    extends HudsonModelLoadStatistics
{

    protected HudsonModelMultiStageTimeSeries totalQueueLength;

    /**
     * Gets the value of the totalQueueLength property.
     * 
     * @return
     *     possible object is
     *     {@link HudsonModelMultiStageTimeSeries }
     *     
     */
    public HudsonModelMultiStageTimeSeries getTotalQueueLength() {
        return totalQueueLength;
    }

    /**
     * Sets the value of the totalQueueLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link HudsonModelMultiStageTimeSeries }
     *     
     */
    public void setTotalQueueLength(HudsonModelMultiStageTimeSeries value) {
        this.totalQueueLength = value;
    }

}
