/*******************************************************************************
 * Copyright (c) 2010 Tasktop Technologies and others.
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 * 
 * SPDX-License-Identifier: EPL-2.0
 *
 *     Tasktop Technologies - initial API and implementation
 *******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 

package org.eclipse.mylyn.internal.hudson.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for hudson.tasks.test.AggregatedTestResultAction complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hudson.tasks.test.AggregatedTestResultAction">
 *   &lt;complexContent>
 *     &lt;extension base="{}hudson.tasks.test.AbstractTestResultAction">
 *       &lt;sequence>
 *         &lt;element name="childReport" type="{}hudson.tasks.test.AggregatedTestResultAction-ChildReport" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hudson.tasks.test.AggregatedTestResultAction", propOrder = { "childReport" })
@XmlSeeAlso({ HudsonMavenReportersSurefireAggregatedReport.class })
@SuppressWarnings("all")
public class HudsonTasksTestAggregatedTestResultAction extends HudsonTasksTestAbstractTestResultAction {

	protected List<HudsonTasksTestAggregatedTestResultActionChildReport> childReport;

	/**
	 * Gets the value of the childReport property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the childReport property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getChildReport().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link HudsonTasksTestAggregatedTestResultActionChildReport }
	 */
	public List<HudsonTasksTestAggregatedTestResultActionChildReport> getChildReport() {
		if (childReport == null) {
			childReport = new ArrayList<HudsonTasksTestAggregatedTestResultActionChildReport>();
		}
		return this.childReport;
	}

}
