    - name: set global var
      ansible.builtin.set_fact:
        grp_prefix: "{{ prefix | default('mylyn')}}"
        mylyn_service_domain: "{{ local_domain | default('mylyn.local')}}"
        docker_swarm_recreate: "{{ swarm_recreate | default(false) }}"
        docker_mode_global: "{{ docker_run_mode | default('container') }}"
        network_ip_matcher: "{{ local_network_ip_matcher | default('^192\\.168\\.64\\..*') }}"
      tags:
        - global
        
    - name: build list 1
      ansible.builtin.set_fact:
        setup_lst_tmp: 
         "{{ groups[grp_prefix + \"_admin\"]  + groups[grp_prefix + \"_swarm_master\"] }}" 
        mylyn_noadmin_vm_hosts: 
         "{{ groups[grp_prefix + \"_swarm_master\"] }}" 
      tags:
        - global

    - name: build list swarm
      ansible.builtin.set_fact:
        setup_lst_tmp:  
         "{{ setup_lst_tmp  +  groups[grp_prefix + \"_swarm_worker\" ] }}"
        mylyn_noadmin_vm_hosts: 
         "{{ mylyn_noadmin_vm_hosts  +  groups[grp_prefix + \"_swarm_worker\" ] }}"
      tags:
        - global
      when: (docker_mode_global == 'swarm' or docker_mode_global == 'all')
    - name: set list admin server
      ansible.builtin.set_fact:
        rootca_server_name: "{{ groups[hostvars['localhost'].grp_prefix + \"_admin\"][0] }}"
        mylyn_service_vm_name: "{{ groups[hostvars['localhost'].grp_prefix + \"_swarm_master\"][0] }}"
      tags:
        - global
    - name: build single
      ansible.builtin.set_fact:
        setup_lst_tmp:  
         "{{ groups[grp_prefix + \"_swarm_master\" ] }}"
        mylyn_noadmin_vm_hosts: 
         "{{ groups[grp_prefix + \"_swarm_master\" ] }}"
        rootca_server_name:
         "{{ mylyn_service_vm_name }}"
      tags:
        - global
      when: (docker_mode_global == 'single')
 
    - name: build mylyn_vm_hosts
      ansible.builtin.set_fact:
        mylyn_vm_hosts: "{{ mylyn_vm_hosts | default([]) + [ { 'name': item, 'ip4': hostvars[item].ansible_host, 'disk':  hostvars[item].multipass_disk, 'memory':  hostvars[item].multipass_memory, 'cpus':  hostvars[item].multipass_cpus, 'launch_extra': hostvars[item].additional_launch_parms } ] }}"
      with_items:
        - "{{ setup_lst_tmp }}"
      tags:
        - global

    - name: build localhostPlatform
      ansible.builtin.set_fact:
        localhostPlatform: "{{ ansible_facts['distribution'] +'/' + ansible_facts['architecture']}}"
      with_items:
        - "{{ setup_lst_tmp }}"
      tags:
        - global
    - name: debug list
      vars:
         msg: |
             rootca_server_name = {{ rootca_server_name }}
             localhostPlatform  = {{ localhostPlatform }}
             all hosts          = {{ mylyn_vm_hosts }}
             all non admin vm   = {{ mylyn_noadmin_vm_hosts }}
             service vm         = {{ mylyn_service_vm_name }}
             service domain     = {{ mylyn_service_domain }}
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
        verbosity: 0
      tags:
         - global
