    - name: set global var
      ansible.builtin.set_fact:
        grp_prefix: "{{ prefix | default('mylyn')}}"
        local_domain: "{{ local_dom | default('mylyn.local')}}"
        remote_domain: "{{ remote_dom | default('public.mydomain.de')}}"
        docker_swarm_recreate: "{{ swarm_recreate | default(false) }}"
        docker_mode_global: "{{ docker_run_mode | default('container') }}"
        network_ip_matcher: "{{ local_network_ip_matcher | default('^192\\.168\\.2\\..*') }}"
      tags:
        - global
        
    - name: build list 1
      ansible.builtin.set_fact:
        setup_lst_tmp: 
         "{{ groups[grp_prefix + \"_admin\"]  + groups[grp_prefix + \"_swarm_master\"] }}" 
        setup_noadmin_vm_list: 
         "{{ groups[grp_prefix + \"_swarm_master\"] }}" 
      tags:
        - global

    - name: build list swarm
      ansible.builtin.set_fact:
        setup_lst_tmp:  
         "{{ setup_lst_tmp  +  groups[grp_prefix + \"_swarm_worker\" ] }}"
        setup_noadmin_vm_list: 
         "{{ setup_noadmin_vm_list  +  groups[grp_prefix + \"_swarm_worker\" ] }}"
      tags:
        - global
      when: (docker_mode_global == 'swarm' or docker_mode_global == 'all')
    - name: set list admin server
      ansible.builtin.set_fact:
        rootca_server_name: "{{ groups[hostvars['localhost'].grp_prefix + \"_admin\"][0] }}"
        prim_install_server_name: "{{ groups[hostvars['localhost'].grp_prefix + \"_swarm_master\"][0] }}"
      tags:
        - global
    - name: build single
      ansible.builtin.set_fact:
        setup_lst_tmp:  
         "{{ groups[grp_prefix + \"_swarm_master\" ] }}"
        setup_noadmin_vm_list: 
         "{{ groups[grp_prefix + \"_swarm_master\" ] }}"
        rootca_server_name:
         "{{ prim_install_server_name }}"
      tags:
        - global
      when: (docker_mode_global == 'single')
 
    - name: build setup_lst
      ansible.builtin.set_fact:
        setup_lst: "{{ setup_lst | default([]) + [ { 'name': item, 'ip4': hostvars[item].ansible_host, 'disk':  hostvars[item].multipass_disk, 'memory':  hostvars[item].multipass_memory, 'cpus':  hostvars[item].multipass_cpus, 'launch_extra': hostvars[item].additional_launch_parms } ] }}"
      with_items:
        - "{{ setup_lst_tmp }}"
      tags:
        - global

    - name: build localhostPlatform
      ansible.builtin.set_fact:
        localhostPlatform: "{{ ansible_facts['distribution'] +'/' + ansible_facts['architecture']}}"
      with_items:
        - "{{ setup_lst_tmp }}"
      tags:
        - global
    - name: debug list
      vars:
         msg: |
             rootca_server_name = {{ rootca_server_name }}
             localhostPlatform = {{ localhostPlatform }}
             all hosts = {{ setup_lst }}
             all non admin vm = {{ setup_noadmin_vm_list }}
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
        verbosity: 0
      tags:
         - global
