#
# set Globale Facts
#
- hosts: localhost
  gather_facts: true
  pre_tasks:
    - include_vars:
        dir: mylyn_vars
        extensions:
        - json
  tasks:
    - name: debug list
      vars:
         msg: |
             all hosts          = {{ mylyn_vm_hosts }}
             all non admin vm   = {{ mylyn_noadmin_vm_hosts }}
             service vm         = {{ mylyn_service_vm_name }}
             service domain     = {{ mylyn_service_domain }}
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
        verbosity: 0
#
# start all non admin Docker Nodes
#
- hosts: "{{ hostvars['localhost'].mylyn_noadmin_vm_hosts }}"
  gather_facts: true
  pre_tasks:
    - include_vars:
        dir: mylyn_vars
        extensions:
        - json
  vars:
    rootca_name: "{{ hostvars['localhost'].rootca_server_name }}"
  tasks:
    - name: Ensure docker deamon is running
      service:
        name: docker
        state: started
      become: true
#
# 1) install Docker Swarm Leader (if needed)
# 2) stop all Docker Services / Container
#
- hosts: "{{ hostvars['localhost'].mylyn_service_vm_name }}"
  gather_facts: false
  pre_tasks:
    - include_vars:
        dir: mylyn_vars
        extensions:
        - json
  vars:
    swarm_master_name: "{{ hostvars['localhost'].mylyn_service_vm_name  }}"
  roles:
    - role: swarm_delete
      when: ((hostvars['localhost'].mylyn_docker_swarm_recreate | bool == true) or (hostvars['localhost'].mylyn_docker_mode_global == "container"))
      tags:
        - mylyn_docker_swarm_recreate
    - role: swarm_setup
      when:  hostvars['localhost'].mylyn_docker_mode_global == "swarm"
      tags:
        - docker_swarm_setup
    - role: swarm_stop
      when: hostvars['localhost'].mylyn_docker_swarm_recreate | bool == false
#
# cleanup all docker instances 
#
- hosts: "{{ hostvars['localhost'].mylyn_noadmin_vm_hosts }}"
  gather_facts: true
  pre_tasks:
    - include_vars:
        dir: mylyn_vars
        extensions:
        - json
  vars:
    rootca_name: "{{ hostvars['localhost'].rootca_server_name }}"
  roles:
    - role: docker_cleanup
      tags:
        - docker_cleanup
#
# Services installieren
# install Docker Services / Container
# 
- hosts: "{{ hostvars['localhost'].mylyn_service_vm_name  }}"
  gather_facts: false
  pre_tasks:
    - include_vars:
        dir: mylyn_vars
        extensions:
        - json
  vars:
    swarm_master_name: "{{ hostvars['localhost'].mylyn_service_vm_name  }}"
    docker_mode: "{{ hostvars['localhost'].mylyn_docker_mode_global }}"
  roles:
    - role: traeefik
      vars:
        common_domain_name: "{{ hostvars['localhost'].mylyn_service_domain }}"
    - role: socket-proxy
    - role: mylyn_idx
      vars:
        common_domain_name: "{{ hostvars['localhost'].mylyn_service_domain }}"
    - role: artifactory
      tags:
        - artifactory
      vars:
        common_domain_name: "{{ hostvars['localhost'].mylyn_service_domain }}"
    - role: gitlab
      tags:
        - gitlab
      vars:
        common_domain_name: "{{ hostvars['localhost'].mylyn_service_domain }}"
        gitlabImageVersion: "17.7.0"
        gitlabHostURL: "gitlab.{{ hostvars['localhost'].mylyn_service_domain }}"
    - role: jenkins
      tags:
        - jenkins
      vars:
        common_domain_name: "{{ hostvars['localhost'].mylyn_service_domain }}"
        jenkins_instances:
          - {  servmame: "jenkins-latest", port1: 8084, port2: 50004, data_dir: "jenkins-2.303.3", image_tag: "jenkins/jenkins:latest", extra_info: '' }
    - role: bugzilla
      tags:
        - bugzilla
      vars:
        common_domain_name: "{{ hostvars['localhost'].mylyn_service_domain }}"
        bugzilla_instances:
          - { git_branch: "release-4.4-stable", servmame: "bugzilla-4_4", port1: 8090, port2: 8490, image_tag: "4.4", extra_info: '"default": "true"' }
#          - { git_branch: "release-4.4-stable", servmame: "bugzilla-4_4-custom-wf", port1: 8091, port2: 8491, image_tag: "4.4-custom_wf", extra_info: '"custom_wf":"true"' }
#          - { git_branch: "release-4.4-stable", servmame: "bugzilla-4_4-custom-wf-and-status", port1: 8092, port2: 8492, image_tag: "4.4-custom_wf_a_s", extra_info: '"custom_wf_and_status":"true"' }
#          - { git_branch: "release-4.4-stable", servmame: "bugzilla-4_4-bugaliases", port1: 8093, port2: 8493, image_tag: "4.4-bugaliases", extra_info: '"use_bug_alias":"true"' }
          - { git_branch: "release-5.2-stable", servmame: "bugzilla-5_2", port1: 8094, port2: 8494, image_tag: "5.2", extra_info: '' }
          - { git_branch: "release-5.2-stable", servmame: "bugzilla-5_2-rest", port1: 8095, port2: 8495, image_tag: "5.2-rest", extra_info: '"rest_enabled":"true", "default": "true", "testdataVersion": "Version1"' }
          - { git_branch: "release-5.2-stable", servmame: "bugzilla-5_2-rest-api", port1: 8096, port2: 8496, image_tag: "5.2-rest-api", extra_info: '"rest_enabled": "true", "api_key_enabled": "true", "testdataVersion": "Version1"' }
