---
- name: Get info on Docker Swarm
  community.docker.docker_swarm_info:
  ignore_errors: true
  register: swarm_info_init
- debug:
    var: swarm_info_init
    verbosity: 3
- name: Init a new swarm with default parameters
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ hostvars[mylyn_service_vm_name].ansible_host }}"
  register: swarm_result
  when: swarm_info_init.docker_swarm_active|bool == false

- name: Get infos on network
  community.docker.docker_network_info:
    name: mylyn_net
  register: network_result

- name: Remove network
  community.docker.docker_network:
    name: mylyn_net
    state: absent
    force: true
  when: network_result.exists and network_result.network.Scope != 'swarm'
  register: network_result_delete

- name: Create a network
  community.docker.docker_network:
    driver: overlay
    scope: swarm
    name: mylyn_net
  when: (not network_result.exists) or (network_result_delete.changed)

- name: Get info on Docker Swarm
  community.docker.docker_swarm_info:
  register: swarm_info
- name: docker_swarm_active
  debug:
    msg: " {{ swarm_info.docker_swarm_active }}"
    verbosity: 3
- debug: var="swarm_info" verbosity=3
- name: glob swarm info
  ansible.builtin.set_fact:
    myWorkerToken: "{{ swarm_info.swarm_facts.JoinTokens.Worker  }}"
    myWorkerManager: "{{ swarm_info.swarm_facts.JoinTokens.Manager  }}"
    mySwarmMaster: "{{ inventory_hostname }}"
  run_once: true
  delegate_to: localhost
  delegate_facts: true

- name: add node to swarm as worker
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars['localhost'].myWorkerToken }}"
    remote_addrs: "{{ hostvars['localhost'].mySwarmMaster }}"
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups[hostvars['localhost'].mylyn_grp_prefix  + \"_swarm_worker\"] }}"
  when: swarm_info_init.docker_swarm_active|bool == false
...