---
- name: Create a network            
  community.docker.docker_network:  
    driver: overlay                 
    scope: swarm                    
    name: cloud-socket-proxy            
  when: ((docker_mode is defined) and (docker_mode == 'swarm'))

- name: Deploy swarm service
  community.docker.docker_swarm_service:
    name: docker-socket-proxy
    image: tecnativa/docker-socket-proxy:latest
    networks:
      - cloud-socket-proxy
    publish:       
      - published_port: "2375"
        target_port: "2375"
    replicas: 1
    update_config:
      parallelism: 1
      delay: 10s
      order: start-first
    restart_config:
      condition: on-failure
      delay: 10s
      max_attempts: 3
      window: 120s
    mounts:
      - source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        type: bind
    env:
      # permssions needed
      NETWORKS: "1"
      SERVICES: "1"
      TASKS: "1"
      CONTAINERS: "1"
      IMAGES: "1"
      VOLUMES: "1"
    placement:
      constraints:
        - node.role == manager
  when: ((docker_mode is defined) and (docker_mode == 'swarm'))
  
- name: Deploy Container
  community.docker.docker_container:
    name: docker-socket-proxy
    image: tecnativa/docker-socket-proxy:latest
    privileged: true
    ports:       
      - "2375:2375"
    networks:
      - name: mylyn_net
    restart: true
    restart_policy: "unless-stopped"
    env:
      NETWORKS: "1"
      SERVICES: "1"
      CONTAINERS: "1"
      IMAGES: "1"
      VOLUMES: "1"   
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  when: ((docker_mode is defined) and (docker_mode == 'container' or docker_mode == 'single' or docker_mode == 'gitlab'))
