/*******************************************************************************
 * Copyright (c) 2010 Tasktop Technologies and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *     Tasktop Technologies - initial API and implementation
 *******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.

package org.eclipse.mylyn.internal.hudson.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for hudson.tasks.test.AggregatedTestResultAction-ChildReport complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="hudson.tasks.test.AggregatedTestResultAction-ChildReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="child" type="{}hudson.model.AbstractBuild" minOccurs="0"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hudson.tasks.test.AggregatedTestResultAction-ChildReport", propOrder = { "child", "result" })
@SuppressWarnings("all")
public class HudsonTasksTestAggregatedTestResultActionChildReport {

	protected HudsonModelAbstractBuild child;

	protected Object result;

	/**
	 * Gets the value of the child property.
	 *
	 * @return possible object is {@link HudsonModelAbstractBuild }
	 */
	public HudsonModelAbstractBuild getChild() {
		return child;
	}

	/**
	 * Sets the value of the child property.
	 *
	 * @param value
	 *            allowed object is {@link HudsonModelAbstractBuild }
	 */
	public void setChild(HudsonModelAbstractBuild value) {
		child = value;
	}

	/**
	 * Gets the value of the result property.
	 *
	 * @return possible object is {@link Object }
	 */
	public Object getResult() {
		return result;
	}

	/**
	 * Sets the value of the result property.
	 *
	 * @param value
	 *            allowed object is {@link Object }
	 */
	public void setResult(Object value) {
		result = value;
	}

}
