/*******************************************************************************
 * Copyright (c) 2010 Tasktop Technologies and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 *     Tasktop Technologies - initial API and implementation
 *******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.

package org.eclipse.mylyn.internal.hudson.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for hudson.matrix.MatrixBuild complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="hudson.matrix.MatrixBuild"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}hudson.model.AbstractBuild"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="run" type="{}hudson.matrix.MatrixRun" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hudson.matrix.MatrixBuild", propOrder = { "run" })
@SuppressWarnings("all")
public class HudsonMatrixMatrixBuild extends HudsonModelAbstractBuild {

	protected List<HudsonMatrixMatrixRun> run;

	/**
	 * Gets the value of the run property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the run property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getRun().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link HudsonMatrixMatrixRun }
	 */
	public List<HudsonMatrixMatrixRun> getRun() {
		if (run == null) {
			run = new ArrayList<>();
		}
		return run;
	}

}
