/*******************************************************************************
 * Copyright (c) 2010 Tasktop Technologies and others.
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 * 
 * SPDX-License-Identifier: EPL-2.0
 *
 *     Tasktop Technologies - initial API and implementation
 *******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.

package org.eclipse.mylyn.internal.hudson.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for hudson.tasks.test.AbstractTestResultAction complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hudson.tasks.test.AbstractTestResultAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="failCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="skipCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="totalCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="urlName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hudson.tasks.test.AbstractTestResultAction", propOrder = { "failCount", "skipCount", "totalCount",
		"urlName" })
@XmlSeeAlso({ HudsonTasksTestAggregatedTestResultAction.class })
@SuppressWarnings("all")
public class HudsonTasksTestAbstractTestResultAction {

	protected int failCount;

	protected int skipCount;

	protected int totalCount;

	protected String urlName;

	/**
	 * Gets the value of the failCount property.
	 */
	public int getFailCount() {
		return failCount;
	}

	/**
	 * Sets the value of the failCount property.
	 */
	public void setFailCount(int value) {
		failCount = value;
	}

	/**
	 * Gets the value of the skipCount property.
	 */
	public int getSkipCount() {
		return skipCount;
	}

	/**
	 * Sets the value of the skipCount property.
	 */
	public void setSkipCount(int value) {
		skipCount = value;
	}

	/**
	 * Gets the value of the totalCount property.
	 */
	public int getTotalCount() {
		return totalCount;
	}

	/**
	 * Sets the value of the totalCount property.
	 */
	public void setTotalCount(int value) {
		totalCount = value;
	}

	/**
	 * Gets the value of the urlName property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getUrlName() {
		return urlName;
	}

	/**
	 * Sets the value of the urlName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setUrlName(String value) {
		urlName = value;
	}

}
