{
 "title": "Traefik Frank",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Mylyn Services",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (traefik_router_requests_total{code=\"200\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mylyn Services calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service) (traefik_service_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mylyn Services %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entrypoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per Entrypoint",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(entrypoint) (rate(traefik_entrypoint_requests_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Duration per Entrypoint",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(entrypoint) (rate(traefik_entrypoint_request_duration_seconds_sum[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Open Connections  per Entrypoint",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
     "targets": [
      { "expr": "traefik_open_connections", "legendFormat": "{{entrypoint}}" }
     ]
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node-exporter\"}))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disk Use %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100)/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})\n#node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}/1000/1000/1000\n#node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}/1000/1000/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk freespace",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (node_filesystem_avail_bytes {fstype!=\"tmpfs\",mountpoint=\"/\"}) / 1024 /1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum (node_filesystem_avail_bytes {fstype!=\"tmpfs\",mountpoint=\"/\"}) / 1024 /1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Code ",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by(method, code) (rate(traefik_service_requests_total{protocol=\"http\"}[1m])) > 0",
       "legendFormat": "{{method}}[{{code}}]"
      }
     ]
    },
    {
     "title": "Requests by service",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count by(service) (rate(traefik_service_requests_total[$__rate_interval]))",
       "legendFormat": "{{ service }}"
      }
     ]
    },
    {
     "title": "Average response time by service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 11, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(traefik_service_request_duration_seconds_sum{}) by (service) / sum(traefik_service_request_duration_seconds_count{}) by (service)",
       "legendFormat": " {{service}}"
      }
     ]
    },
    {
     "title": "Certificate Dates",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "targets": [
      {
       "expr": "traefik_tls_certs_not_after{san=~\".*\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Routers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per Router",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(router) (rate(traefik_router_requests_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Duration per Router",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(service) (rate(traefik_router_request_duration_seconds_count[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request size  per Router",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "label_replace(sum by(service) (rate(traefik_service_responses_bytes_total[$__rate_interval])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "2xx over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, sum by(service, code, method) (rate(traefik_service_requests_total{code=~\"2..\", protocol=\"http\"}[5m])))",
     "legendFormat": "{{service}} {{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "5xx over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, label_replace(sum by(service, method, code) (rate(traefik_service_requests_total{code=~\"5..\", protocol=\"http\"}[5m])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"))",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Other codes over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, label_replace(sum by(service, method, code) (rate(traefik_service_requests_total{code!~\"2..|5..\", protocol=\"http\"}[5m])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"))",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15, label_replace(sum by(service, method) (rate(traefik_service_requests_bytes_total{protocol=\"http\"}[1m])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"))",
     "legendFormat": "{{method}} on {{service}}"
    }
   ]
  },
  {
   "title": "Responses Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15, label_replace(sum by(service, method) (rate(traefik_service_responses_bytes_total{protocol=\"http\"}[1m])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"))",
     "legendFormat": "{{method}} on {{service}}"
    }
   ]
  }
 ]
}