Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network "forwarded_port", guest:  80, host: 2080
  config.vm.network "forwarded_port", guest: 443, host: 2443
  
  config.vm.provider "virtualbox" do |v|
    v.name = "Mylyn Tasks - Trac Repositories"
  end
  
  config.vm.provision :puppet, :module_path => "modules"
end
