Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64"

  config.vm.network "forwarded_port", guest:  80, host: 2080
  config.vm.network "forwarded_port", guest: 443, host: 2443
  
  config.vm.provider "virtualbox" do |v|
    v.name = "Mylyn Tasks - Bugzilla Repositories"
  end
  
  config.vm.provision :puppet, :module_path => "modules"
#  , :options => "--verbose --debug"
end