Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-14.04-x86_64"
  config.vm.box_url = "http://mylyn.org/files/boxes/ubuntu-14.04-x86_64.box"

  config.vm.network "forwarded_port", guest:  80, host: 2080
  config.vm.network "forwarded_port", guest: 443, host: 2443
  
  config.vm.provider "virtualbox" do |v|
    v.name = "Mylyn Builds - Hudson and Jenkins Repositories"
  end
  
  config.vm.provision :puppet, :module_path => "modules"
end
