---
- name: get multipass instances
  ansible.builtin.shell: multipass list --format json
  register: multipass_instances
  ignore_errors: true
- name: json obj
  ansible.builtin.set_fact:
    inst_json_obj: "{{ multipass_instances.stdout | from_json}}"
- name: inst_list
  ansible.builtin.set_fact:
    inst_list: "{{ inst_json_obj.list | json_query(jmesquery) }}"
  vars:
    jmesquery: "[*].{inst_name: name, inst_state: state, ip_adr4: ipv4[0], ip_adr4a: ipv4[1]}"

- name: json ipadr
  ansible.builtin.set_fact:
    inst_ipadr_list: "{{ inst_json_obj.list | json_query(jmesquery) | list() }}"
  vars:
    jmesquery: "[?name== '{{mylyn_service_vm_name}}'].ipv4"
- name: mylyn_network_ip
  ansible.builtin.set_fact:
    mylyn_network_ip: "{{ item }}"
  when: item is regex(network_ip_matcher)
  with_items: "{{ inst_ipadr_list}}"