- name: Recursively remove directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true 
  loop:
    - /mylyn-config-dir/{{ role_name }}
    - /mylyn-runtime-dir/{{ role_name }}

- name: Creates directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  loop:
    - /mylyn-config-dir/{{ role_name }}
    - /mylyn-runtime-dir/{{ role_name }}

#- name: "Copy latest file(s)"
#  synchronize:
#    delete: yes
#    src: files/
#    dest: /mylyn-config-dir/{{ role_name }}/
#    recursive: yes

#- name: setlabels 
#  ansible.builtin.set_fact:
#    label_data: 
#       { traefik.enable: "true",
#         traefik.docker.network: "mylyn_net",
#         traefik.http.routers.prometheus_https.rule: "Host(`{{ common_domain_name }}`)  && PathPrefix(`/prometheus`)",
#         traefik.http.routers.prometheus_https.entrypoints: "websecure", 
#         traefik.http.routers.prometheus_https.tls: "true",
#         traefik.http.routers.prometheus_https.service: "prometheus",
#         traefik.http.services.prometheus.loadbalancer.server.port: "9090",
#       }
# traefik.http.routers.prometheus_https.middlewares: "stripprefix_prometheus",
# traefik.http.middlewares.stripprefix_prometheus.stripprefix.prefixes: "/prometheus",
# traefik.http.services.prometheus.loadbalancer.passhostheader: "true"

- name: Pull image
  community.docker.docker_image:
    name: "prom/node-exporter:v1.9.1"
    source: pull

- name: Deploy Container
  community.docker.docker_container:
    name: "node-exporter"
    image: "prom/node-exporter:v1.9.1"
    networks:
      - name: mylyn_net
    restart: true
    ports:
      - "9100:9100"
    restart_policy: "unless-stopped"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
