<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="builds"
    nsURI="http://eclipse.org/mylyn/models/build" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="BuildModel" eSuperTypes="#//IBuildModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="BuildPlan" eSuperTypes="#//IBuildPlan"/>
  <eClassifiers xsi:type="ecore:EClass" name="BuildServer" eSuperTypes="#//IBuildServer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
        eType="#//BuildServer" changeable="false" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBuildModel" instanceClassName="org.eclipse.mylyn.builds.core.IBuildModel"
      abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="servers" upperBound="-1"
        eType="#//IBuildServer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBuildElement" instanceClassName="org.eclipse.mylyn.builds.core.IBuildElement"
      abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBuildPlan" instanceClassName="org.eclipse.mylyn.builds.core.IBuildPlan"
      abstract="true" interface="true" eSuperTypes="#//IBuildElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
        eType="#//IBuildServer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//IBuildPlan" eOpposite="#//IBuildPlan/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//IBuildPlan"
        eOpposite="#//IBuildPlan/children"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="info" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//BuildState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBuildServer" instanceClassName="org.eclipse.mylyn.builds.core.IBuildServer"
      abstract="true" interface="true" eSuperTypes="#//IBuildElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plans" ordered="false"
        upperBound="-1" eType="#//IBuildPlan" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repository" eType="#//TaskRepository"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectorKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TaskRepository" instanceClassName="org.eclipse.mylyn.tasks.core.TaskRepository"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BuildState">
    <eLiterals name="RUNNING" literal="RUNNING"/>
    <eLiterals name="STOPPED" literal="STOPPED"/>
  </eClassifiers>
</ecore:EPackage>
