/*
 * generated by Xtext
 */
package org.eclipse.mylyn.reviews.tasks.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ReviewDslRuntimeModule extends org.eclipse.mylyn.reviews.tasks.dsl.AbstractReviewDslRuntimeModule {

}
