---
- name: add etc hosts if not included {{ act_name.name }}
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{  item.ip4 + ' ' +  hostvars[item.name].default_etc_hosts }}"
    insertafter: EOF
  loop: "{{ setup_lst }}"
  delegate_to: "{{ act_name.name }}"
