---
- name: remove mylyn from etc hosts {{ act_name.name }}
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{'^.*mylyn.*' }}"
    state: absent
  delegate_to: "{{ act_name.name }}"

- name: add mylyn to etc hosts if not included {{ act_name.name }}
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{  item.ip4 + ' ' +  hostvars[item.name].default_etc_hosts }}"
    insertafter: EOF
  loop: "{{ mylyn_vm_hosts }}"
  delegate_to: "{{ act_name.name }}"
