Vagrant.configure("2") do |config|
#  config.vm.box = "ubuntu-14.04-x86_64"
#  config.vm.box_url = "http://mylyn.org/files/boxes/ubuntu-14.04-x86_64.box"
  config.vm.box = "mylyn_openjdk8"
  config.vm.box_url = "http://mylyn.org/files/boxes/mylyn_openjdk8.box"

  config.vm.network "forwarded_port", guest:  80, host: 2080
  config.vm.network "forwarded_port", guest: 443, host: 2443

  config.vm.provider "virtualbox" do |v|
     v.name = "Mylyn - All Repositories"
     v.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.provision "puppet" do |puppet_bugzilla|
    puppet_bugzilla.module_path = "../../../org.eclipse.mylyn.tasks/org.eclipse.mylyn.bugzilla.releng/modules"
    puppet_bugzilla.manifests_path = "../../../org.eclipse.mylyn.tasks/org.eclipse.mylyn.bugzilla.releng/manifests"
    puppet_bugzilla.manifest_file = "default.pp"
  end

  config.vm.provision "puppet" do |puppet_hudson|
    puppet_hudson.module_path = "../../../org.eclipse.mylyn.builds/org.eclipse.mylyn.jackson.releng/modules"
    puppet_hudson.manifests_path = "../../../org.eclipse.mylyn.builds/org.eclipse.mylyn.jackson.releng/manifests"
    puppet_hudson.manifest_file = "default.pp"
  end

#  config.vm.provision "puppet" do |puppet_gerrit|
#    puppet_gerrit.module_path = "../../../org.eclipse.mylyn.reviews/org.eclipse.mylyn.gerrit.releng/modules"
#    puppet_gerrit.manifests_path = "../../../org.eclipse.mylyn.reviews/org.eclipse.mylyn.gerrit.releng/manifests"
#    puppet_gerrit.manifest_file = "default.pp"
#  end

#  config.vm.provision "puppet" do |puppet_trac|
#    puppet_trac.module_path = "../../../org.eclipse.mylyn.tasks/org.eclipse.mylyn.trac.releng/modules"
#    puppet_trac.manifests_path = "../../../org.eclipse.mylyn.tasks/org.eclipse.mylyn.trac.releng/manifests"
#    puppet_trac.manifest_file = "default.pp"
#  end

  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "modules"
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "default.pp"
  end
end
