Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  config.vm.provision :puppet, :module_path => [ "../../../org.eclipse.mylyn.tasks/org.eclipse.mylyn.trac.releng/modules" ] 
  config.vm.provision :shell, :path => "scripts/start.sh"

  config.vm.forward_port 80, 2080
  config.vm.forward_port 443, 2443
end
